basePath: /
definitions:
  handlers.QuestRequest:
    properties:
      session_id:
        type: string
      user_answer:
        type: string
    type: object
  models.User:
    description: User model
    properties:
      email:
        example: testuser@example.com
        type: string
      password:
        example: "12345678"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления пользователями
  title: Razbudilius API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Авторизует пользователя по имени и паролю
      parameters:
      - description: Данные для авторизации
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Аутентификация пользователя
      tags:
      - auth
  /process_answer:
    post:
      consumes:
      - application/json
      description: Send user's response and get next step of an existring quest
      parameters:
      - description: Ответ пользователя
        in: body
        name: Answer
        required: true
        schema:
          $ref: '#/definitions/handlers.QuestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Next step
      tags:
      - Quest
  /profile:
    get:
      consumes:
      - application/json
      description: Получает информацию о пользователе на основе токена, сохраненного
        в куки
      parameters:
      - description: Access Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение информации о пользователе
      tags:
      - auth
  /refresh:
    get:
      consumes:
      - application/json
      description: Refreshes the access token using a valid refresh token
      parameters:
      - description: Refresh Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"access_token": "new_access_token", "refresh_token": "new_refresh_token"}'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: '{"error": "Refresh token is required"}'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: '{"error": "Invalid refresh token"}'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: '{"error": "Could not generate token"}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh access token
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя с указанной почтой и паролем
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Регистрация нового пользователя
      tags:
      - auth
  /start_quest:
    get:
      consumes:
      - application/json
      description: Get first step of a new quest
      parameters:
      - description: Сложность квеста (30s/1m/5m)
        in: query
        name: dif
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get quest
      tags:
      - Quest
swagger: "2.0"
